name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup Python and deps
        run: |
          uv python install 3.11
          uv sync --all-extras --dev

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Format check (black)
        run: uv run black --check .

      - name: Type check (mypy)
        run: uv run mypy .

      - name: Tests
        run: uv run pytest -q
